
interface actionItem {
  id: string;
  name: string;
  synonyms: string[];
}

export const volumeActions: actionItem[] = [
  {
    id: "up",
    name: "Aumentar volume",
    synonyms: [
      "cima",
      "alto",
      "subir",
      "acima",
      "mais",
      "aumenta",
      "maior",
      "crescer",
      "incrementar",
      "potente",
      "para cima",
    ],
  },
  {
    id: "down",
    name: "Diminuir volume",
    synonyms: [
      "baixo",
      "baixa",
      "embaixo",
      "diminuir",
      "menos",
      "reduzir",
      "pequeno",
      "descer",
      "para baixo",
      "menos alto",
      "atenuar",
    ],
  },
  {
    id: "mute",
    name: "Mudo",
    synonyms: [
      "mudo",
      "silêncio",
      "sem som",
      "parar",
      "silencioso",
      "calado",
      "desligar som",
      "pausar",
      "quieto",
      "abafar",
    ],
  },
  {
    id: "0.1",
    name: "Volume 10%",
    synonyms: [
      "1",
      "um",
      "primeiro",
      "mínimo",
      "mínima",
      "dez por cento",
      "10%",
      "dez",
      "primeira",
      "baixíssimo",
      "baixíssima",
    ],
  },
  {
    id: "0.2",
    name: "Volume 20%",
    synonyms: [
      "2",
      "dois",
      "segundo",
      "vinte por cento",
      "20%",
      "vinte",
      "segunda",
    ],
  },
  {
    id: "0.3",
    name: "Volume 30%",
    synonyms: [
      "3",
      "três",
      "terceiro",
      "trinta por cento",
      "30%",
      "trinta",
      "terceira",
      "baixo-moderado",
    ],
  },
  {
    id: "0.4",
    name: "Volume 40%",
    synonyms: [
      "4",
      "quatro",
      "quarto",
      "quarenta por cento",
      "40%",
      "quarenta",
      "quarta",
    ],
  },
  {
    id: "0.5",
    name: "Volume 50%",
    synonyms: [
      "5",
      "cinco",
      "quinto",
      "cinquenta por cento",
      "50%",
      "cinquenta",
      "quinta",
      "metade",
    ],
  },
  {
    id: "0.6",
    name: "Volume 60%",
    synonyms: [
      "6",
      "seis",
      "sexto",
      "sessenta por cento",
      "60%",
      "sessenta",
      "sexta",
    ],
  },
  {
    id: "0.7",
    name: "Volume 70%",
    synonyms: [
      "7",
      "sete",
      "sétimo",
      "setenta por cento",
      "70%",
      "setenta",
      "sétima",
    ],
  },
  {
    id: "0.8",
    name: "Volume 80%",
    synonyms: [
      "8",
      "oito",
      "oitavo",
      "oitenta por cento",
      "80%",
      "oitenta",
      "oitava",
      "alto",
    ],
  },
  {
    id: "0.9",
    name: "Volume 90%",
    synonyms: [
      "9",
      "nove",
      "nono",
      "noventa por cento",
      "90%",
      "noventa",
      "nona",
      "muito alto",
    ],
  },
  {
    id: "1",
    name: "Volume 100%",
    synonyms: [
      "10",
      "cem",
      "cento",
      "100%",
      "máximo",
      "máxima",
      "cem por cento",
      "cien",
      "alto total",
      "completo",
    ],
  },
  {
    id: "default",
    name: "default",
    synonyms: [],
  },
];

export const tvActions: actionItem[] = [
  {
    id: "power",
    name: "Ligar/Desligar TV",
    synonyms: ["liga", "desliga", "power", "liga a tv", "desliga a tv"],
  },
  {
    id: "mute",
    name: "Mudo",
    synonyms: ["mudo", "silêncio", "sem som", "parar", "silencioso", "calado"],
  },
  {
    id: "volume_up",
    name: "Aumentar volume",
    synonyms: ["cima", "alto", "subir", "acima", "mais", "aumenta", "maior"],
  },
  {
    id: "volume_down",
    name: "Diminuir volume",
    synonyms: ["baixo", "baixa", "embaixo", "diminuir", "menos", "reduzir"],
  },
  {
    id: "channel_up",
    name: "Canal anterior",
    synonyms: ["próximo", "avançar", "seguinte", "seguinte", "avançar canal"],
  },
  {
    id: "channel_down",
    name: "Canal seguinte",
    synonyms: ["anterior", "retroceder", "voltar", "canal anterior"],
  },
];